### ISSUE TITLE
Image stretched on IE

### ISSUE THREAD

**Issue by trevorjonesd2l** [Brightspace/d2l-my-courses-ui#123]
How it should look:
![image](https://cloud.githubusercontent.com/assets/8656538/18641805/3313db06-7e6c-11e6-9a8b-ebcbd097cfae.png)

How it looks on IE:
![image](https://cloud.githubusercontent.com/assets/8656538/18641813/3a049798-7e6c-11e6-8498-179cc140a1ba.png)

**Comment by ryantmer** [comment]
This is as a result of IE (and Edge as well, apparently) not supporting [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit). It's [under consideration](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/objectfitandobjectposition/) for Edge, but won't be supported in IE11. Not sure if this means we wait until it's supported (and ignore IE11 because who cares), or [polyfill it](https://github.com/bfred-it/object-fit-images/)...

**Comment by ryantmer** [comment]
Seems like this has been solved... somehow. Closing as images look fine now in IE.
