### ISSUE TITLE
Filter dropdown loses focus

### ISSUE THREAD

**Issue by ryantmer** [Brightspace/d2l-my-courses-ui#126]
If you click inside the filter dropdown on something that isn't "selectable" (e.g. the scrollbar, or the checkbox text), the dropdown loses focus. iirc this is a bug in `iron-overlay-behavior`.

Might also be related to (or, in fact, the same problem as) the fact that the checkbox labels don't check/uncheck the checkboxes.

**Comment by apalaniuk** [comment]
@ryantmer I think it's because `d2l-simple-overlay` gains focus (regardless of any `iron-overlay-behavior` handlers), and `d2l-dropdown-content::__onAutoCloseFocus` expects `body` to be the active element if you don't click on a selectable element, but haven't clicked outside of the dropdown (which is what happens with d2l-navigation).

**Comment by ryantmer** [comment]
@apalaniuk Is this what was addressed in https://github.com/Brightspace/d2l-polymer-behaviors-ui/pull/7? Didn't really look that closely granted, so ignore me if it's completely unrelated :P

**Comment by apalaniuk** [comment]
@ryantmer Doesn't directly address it, but necessary. That's in a PR for d2l-dropdown I'm putting up momentarily.

**Comment by ryantmer** [comment]
Confirmed that this was indeed fixed by https://github.com/Brightspace/d2l-dropdown-ui/pull/79, which was released in [v2.2.4](https://github.com/Brightspace/d2l-dropdown-ui/releases/tag/v2.2.4), which [we're using here](https://github.com/Brightspace/d2l-my-courses-ui/blob/master/bower.json#L34)
